{
 "title": "AWS Route53",
 "description": "Visualize AWS Route53 Asset Inventory across accounts and regions.",
 "tags": [
  "aws",
  "route53"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "account_ids",
    "query": "select account_id from aws_accounts"
   }
  ]
 },
 "panels": [
  {
   "title": "count aws_route53_domains by account_id",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 5, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select account_id, count(*) from aws_route53_domains group by account_id"
    }
   ]
  },
  {
   "title": "count aws_route53_domains",
   "type": "stat",
   "gridPos": { "h": 7, "w": 5, "x": 5, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select count(*) from aws_route53_domains where account_id in (${account_ids})"
    }
   ]
  },
  {
   "title": "count aws_route53_domains",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 5, "x": 10, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select count(*) from aws_route53_domains where account_id in (${account_ids})"
    }
   ]
  },
  {
   "title": "aws_route53_domains",
   "type": "table",
   "gridPos": { "h": 7, "w": 9, "x": 15, "y": 0 },
   "targets": [
    {
     "rawSql": "select * from aws_route53_domains where account_id in (${account_ids})"
    }
   ]
  },
  {
   "title": "count aws_route53_hosted_zones by account_id",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 5, "x": 0, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select account_id, count(*) from aws_route53_hosted_zones group by account_id"
    }
   ]
  },
  {
   "title": "count aws_route53_hosted_zones",
   "type": "stat",
   "gridPos": { "h": 7, "w": 5, "x": 5, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select count(*) from aws_route53_hosted_zones where account_id in (${account_ids})"
    }
   ]
  },
  {
   "title": "count aws_route53_hosted_zones",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 5, "x": 10, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select count(*) from aws_route53_hosted_zones where account_id in (${account_ids})"
    }
   ]
  },
  {
   "title": "aws_route53_hosted_zones",
   "type": "table",
   "gridPos": { "h": 7, "w": 9, "x": 15, "y": 7 },
   "targets": [
    {
     "rawSql": "select * from aws_route53_hosted_zones where account_id in (${account_ids})"
    }
   ]
  },
  {
   "title": "count aws_route53_traffic_policies by account_id",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 5, "x": 0, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select account_id, count(*) from aws_route53_traffic_policies group by account_id"
    }
   ]
  },
  {
   "title": "count aws_route53_traffic_policies",
   "type": "stat",
   "gridPos": { "h": 7, "w": 5, "x": 5, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select count(*) from aws_route53_traffic_policies where account_id in (${account_ids})"
    }
   ]
  },
  {
   "title": "count aws_route53_traffic_policies",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 5, "x": 10, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select count(*) from aws_route53_traffic_policies where account_id in (${account_ids})"
    }
   ]
  },
  {
   "title": "aws_route53_traffic_policies",
   "type": "table",
   "gridPos": { "h": 7, "w": 9, "x": 15, "y": 14 },
   "targets": [
    {
     "rawSql": "select * from aws_route53_traffic_policies where account_id in (${account_ids})"
    }
   ]
  }
 ]
}