{
 "title": "AWS RDS",
 "description": "Visualize AWS RDS Asset Inventory across accounts and regions.",
 "tags": [
  "aws",
  "rds"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "account_ids",
    "query": "select account_id from aws_accounts"
   },
   {
    "name": "regions",
    "query": "us-east-2,us-east-1,us-west-1,us-west-2,af-south-1,ap-east-1,ap-south-1,ap-northeast-3,ap-northeast-2,ap-southeast-1,ap-southeast-2,ap-northeast-1,ca-central-1,eu-central-1,eu-west-1,eu-west-2,eu-south-1,eu-west-3,eu-north-1,me-south-1,sa-east-1"
   }
  ]
 },
 "panels": [
  {
   "title": "count aws_rds_instances by account_id",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 5, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select account_id, count(*) from aws_rds_instances group by account_id"
    }
   ]
  },
  {
   "title": "count aws_rds_instances",
   "type": "stat",
   "gridPos": { "h": 7, "w": 5, "x": 5, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select count(*) from aws_rds_instances where account_id in (${account_ids}) and region in (${regions})"
    }
   ]
  },
  {
   "title": "count aws_rds_instances by region",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 5, "x": 10, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select region, count(*) from aws_rds_instances where account_id in (${account_ids}) and region in (${regions}) group by region"
    }
   ]
  },
  {
   "title": "aws_rds_instances",
   "type": "table",
   "gridPos": { "h": 7, "w": 9, "x": 15, "y": 0 },
   "targets": [
    {
     "rawSql": "select * from aws_rds_instances where account_id in (${account_ids}) and region in (${regions})"
    }
   ]
  },
  {
   "title": "count aws_rds_clusters by account_id",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 5, "x": 0, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select account_id, count(*) from aws_rds_clusters group by account_id"
    }
   ]
  },
  {
   "title": "count aws_rds_clusters",
   "type": "stat",
   "gridPos": { "h": 7, "w": 5, "x": 5, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select count(*) from aws_rds_clusters where account_id in (${account_ids}) and region in (${regions})"
    }
   ]
  },
  {
   "title": "count aws_rds_clusters by region",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 5, "x": 10, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select region, count(*) from aws_rds_clusters where account_id in (${account_ids}) and region in (${regions}) group by region"
    }
   ]
  },
  {
   "title": "aws_rds_clusters",
   "type": "table",
   "gridPos": { "h": 7, "w": 9, "x": 15, "y": 7 },
   "targets": [
    {
     "rawSql": "select * from aws_rds_clusters where account_id in (${account_ids}) and region in (${regions})"
    }
   ]
  }
 ]
}