{
 "title": "Cluster view - CPU and Mem2",
 "description": "Total view of the AWS cluster ",
 "time": { "from": "2019-05-26T08:59:20.663Z", "to": "2019-05-26T08:59:55.262Z" },
 "templating": {
  "list": [
   {
    "name": "namespace",
    "label": "Namespace",
    "query": "label_values(kube_pod_info,namespace)"
   },
   { "name": "service", "label": "service", "query": "label_values(image)" },
   { "name": "podname", "label": "Podname", "query": "label_values(pod_name)" },
   { "name": "container", "label": "container_name", "query": "label_values(container_name)" }
  ]
 },
 "panels": [
  {
   "title": "Available Cores",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": " sum(kube_node_status_allocatable_cpu_cores)"
    }
   ]
  },
  {
   "title": "Used Cores",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_user_seconds_total[5m]))/sum(kube_node_status_allocatable_cpu_cores)*100"
    }
   ]
  },
  {
   "title": "Used Cores",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 7, "x": 16, "y": 0 },
   "targets": [
    {
     "expr": " sum(rate(container_cpu_user_seconds_total[10m]))"
    }
   ]
  },
  {
   "title": "CPU consumtion",
   "type": "graph",
   "description": "Total CPU use ",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(container_cpu_user_seconds_total{namespace=~\"$namespace\",image=~\"$service\", pod_name=~\"$podname\",container_name=~\"$container\"}[5m])",
     "legendFormat": "namespace:{{namespace}} pod:{{pod_name}}"
    }
   ]
  },
  {
   "title": "Memory consumption",
   "type": "graph",
   "description": "All cluster view",
   "gridPos": { "h": 15, "w": 24, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_memory_working_set_bytes{namespace=~\"$namespace\",image=~\"$service\", pod_name=~\"$podname\",container_name=~\"$container\"}[5m])) by (pod_name)",
     "legendFormat": "{{pod_name}}"
    }
   ]
  }
 ]
}