{
 "title": "Kubernetes / Compute Resources / Node (Groups)",
 "description": "Custom - Grafana dashboard to monitoring nodes grouped by AWS EKS nodegroup. Bear in mind you need a kubernetes label called \"nodegroup\" in each compute < Node Groups",
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "nodegroup",
    "query": {
     "query": "label_values(alpha_eksctl_io_nodegroup_name)"
    }
   },
   {
    "name": "node",
    "query": {
     "query": "label_values(kubelet_node_name{alpha_eksctl_io_nodegroup_name =~ \"$nodegroup\"}, instance)"
    }
   },
   {
    "name": "instance",
    "query": {
     "query": "label_values(kube_pod_info{node =~ \"$node\"}, host_ip)"
    }
   },
   { "name": "interval", "label": "Interval", "query": "1m,2m,3m,5m,10m,30m" }
  ]
 },
 "panels": [
  {
   "title": "Total Nodes",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(kube_node_info{exported_node=~\"$node\"}) by (node)",
     "legendFormat": "{{ node }}"
    }
   ]
  },
  {
   "title": "Pod Count - Total",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_info{exported_node=~\"$node\"})"
    }
   ]
  },
  {
   "title": "Pod Count  - State",
   "type": "stat",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum (kube_pod_status_phase{}) by (phase) ",
     "legendFormat": "{{ phase }}"
    },
    {
     "expr": "kubelet_running_pod_count{kubernetes_io_role =~ \".*node.*\"}",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "CPU Utilization",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "(1 - (sum(rate(node_cpu_seconds_total{node=~\"$node\", mode=\"idle\"}[$interval])) by (node) / sum(rate(node_cpu_seconds_total{node=~\"$node\"}[$interval])) by (node))) * 100",
     "legendFormat": "{{node}}-cpu-utilization"
    }
   ]
  },
  {
   "title": "Memory Utilization",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 6 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "(node_memory_MemTotal_bytes{node=~\"$node\"} - node_memory_MemAvailable_bytes{node=~\"$node\"}) / node_memory_MemTotal_bytes{node=~\"$node\"} * 100",
     "legendFormat": "{{instance}}-memory-utilization"
    }
   ]
  },
  {
   "title": "Disk Utilization",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "(sum (node_filesystem_size_bytes{node=~\"$node\"}) by (node) - sum (node_filesystem_free_bytes{node=~\"$node\"}) by (node)) / sum (node_filesystem_size_bytes{node=~\"$node\"}) by (node) * 100",
     "legendFormat": "{{kubernetes_node}}-disk-utilization"
    }
   ]
  },
  {
   "title": "Disk I/O",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 15 },
   "yaxes": [
    { "format": "mbytes" }
   ],
   "targets": [
    {
     "expr": "sum(rate(node_disk_read_bytes_total{node=~\"$node\"}[$interval]) / (1024 * 1024)) by (node)",
     "legendFormat": "{{node}}-read-bytes"
    },
    {
     "expr": "sum(rate(node_disk_written_bytes_total{node=~\"$node\"}[$interval]) / (1024 * 1024)) by (node)",
     "legendFormat": "{{node}}-write-bytes"
    }
   ]
  },
  {
   "title": "Network I/O",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 15 },
   "yaxes": [
    { "format": "mbytes" }
   ],
   "targets": [
    {
     "expr": "sum(rate(node_network_receive_bytes_total{node=~\"$node\",device=~\"eth.*\"}[$interval]) / (1024 * 1024)) by (node)",
     "legendFormat": "{{node}}-network-in"
    },
    {
     "expr": "sum(rate(node_network_transmit_bytes_total{node=~\"$node\",device=~\"eth.*\"}[$interval]) / (1024 * 1024)) by (node)",
     "legendFormat": "{{node}}-network-out"
    }
   ]
  },
  {
   "title": "Load Avg (1m)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "node_load1{node=~\"$node\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Load Avg (5m)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "node_load5{node=~\"$node\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Load Avg (15m)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "node_load15{node=~\"$node\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  }
 ]
}