version: '3.6'
services:
  influxdb:
    image: influxdb
    container_name: influxdb
    build: 
      context: ./influxdb/2.2/
      dockerfile: Dockerfile
    env_file: 
      - configuration.env
    ports:
      - '8086:8086' 
    volumes: 
      - influxdb_data:/var/lib/influxdb 

  grafana:
    image: grafana
    container_name: grafana_ui
    build:
      context: ./grafana/8.5.4/
      dockerfile: Dockerfile
    depends_on:
      - influxdb
    env_file: 
      - configuration.env
    links:
      - influxdb 
    ports:
      - '3000:3000' 
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/provisioning/:/etc/grafana/provisioning/

  telegraf: 
    image: telegraf
    container_name: telegraf_agent
    env_file: 
      - configuration.env
    build: 
      context: ./telegraf/etc/1.22/
      dockerfile: Dockerfile  
    volumes:
      - ./telegraf/telegraf.conf:/etc/telegraf/telegraf.conf
    depends_on:
      - influxdb
    links:
      - influxdb
    ports:  
      - "8125:8125"
      - '8125:8125/udp'

volumes:
  grafana_data: {}
  influxdb_data: {}
