apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: /snap/kompose/19/kompose-linux-amd64 convert -f docker-compose.yml
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: influxdb
  name: influxdb
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: influxdb
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: /snap/kompose/19/kompose-linux-amd64 convert -f docker-compose.yml
        kompose.version: 1.21.0 (992df58d8)
      creationTimestamp: null
      labels:
        io.kompose.service: influxdb
    spec:
      containers:
      - env:
        - name: DOCKER_INFLUXDB_INIT_ADMIN_TOKEN
          valueFrom:
            configMapKeyRef:
              key: DOCKER_INFLUXDB_INIT_ADMIN_TOKEN
              name: env-influx
        - name: DOCKER_INFLUXDB_INIT_BUCKET
          valueFrom:
            configMapKeyRef:
              key: DOCKER_INFLUXDB_INIT_BUCKET
              name: env-influx
        - name: DOCKER_INFLUXDB_INIT_MODE
          valueFrom:
            configMapKeyRef:
              key: DOCKER_INFLUXDB_INIT_MODE
              name: env-influx
        - name: DOCKER_INFLUXDB_INIT_ORG
          valueFrom:
            configMapKeyRef:
              key: DOCKER_INFLUXDB_INIT_ORG
              name: env-influx
        - name: DOCKER_INFLUXDB_INIT_PASSWORD
          valueFrom:
            configMapKeyRef:
              key: DOCKER_INFLUXDB_INIT_PASSWORD
              name: env-influx
        - name: DOCKER_INFLUXDB_INIT_RETENTION
          valueFrom:
            configMapKeyRef:
              key: DOCKER_INFLUXDB_INIT_RETENTION
              name: env-influx
        - name: DOCKER_INFLUXDB_INIT_USERNAME
          valueFrom:
            configMapKeyRef:
              key: DOCKER_INFLUXDB_INIT_USERNAME
              name: env-influx
        image: influxdb:2.2.0-alpine
        imagePullPolicy: ""
        name: influxdb
        ports:
        - containerPort: 8086
        resources: {}
        securityContext:
          privileged: true
        volumeMounts:
        - mountPath: /var/lib/influxdb2
          name: influxdb-lib
      restartPolicy: Always
      serviceAccountName: ""
      volumes:
      - name: influxdb-lib
        persistentVolumeClaim:
          claimName: influxdb-lib
status: {}
