apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: /snap/kompose/19/kompose-linux-amd64 convert -f docker-compose.yml
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: influxdb-cli
  name: influxdb-cli
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: influxdb-cli
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: /snap/kompose/19/kompose-linux-amd64 convert -f docker-compose.yml
        kompose.version: 1.21.0 (992df58d8)
      creationTimestamp: null
      labels:
        io.kompose.service: influxdb-cli
    spec:
      containers:
      - command:
        - influx
        - -host
        - influxdb
        image: influxdb
        imagePullPolicy: ""
        name: influxdb-cli
        resources: {}
      restartPolicy: Always
      serviceAccountName: ""
      volumes: null
status: {}
