apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: /snap/kompose/19/kompose-linux-amd64 convert -f docker-compose.yml
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: kapacitor-cli
  name: kapacitor-cli
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: kapacitor-cli
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: /snap/kompose/19/kompose-linux-amd64 convert -f docker-compose.yml
        kompose.version: 1.21.0 (992df58d8)
      creationTimestamp: null
      labels:
        io.kompose.service: kapacitor-cli
    spec:
      containers:
      - command:
        - bash
        env:
        - name: KAPACITOR_URL
          value: http://kapacitor:9092
        image: kapacitor
        imagePullPolicy: ""
        name: kapacitor
        resources: {}
      restartPolicy: Always
      serviceAccountName: ""
      volumes: null
status: {}
