apiVersion: 1
datasources:
- name: InfluxDB
  type: influxdb
  orgId: 1 
  access: proxy
  url: http://influxdb:8086
  basicAuth: false
  isDefault: true
  jsonData:
    timeInterval: "10s"
    defaultBucket: $DOCKER_INFLUXDB_INIT_BUCKET
    httpMode: POST
    organization: $DOCKER_INFLUXDB_INIT_ORG
    version: Flux
  secureJsonData:
    token: $DOCKER_INFLUXDB_INIT_ADMIN_TOKEN
