apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: /snap/kompose/19/kompose-linux-amd64 convert -f docker-compose.yml
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: influxdb
  name: influxdb
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: influxdb
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: /snap/kompose/19/kompose-linux-amd64 convert -f docker-compose.yml
        kompose.version: 1.21.0 (992df58d8)
      creationTimestamp: null
      labels:
        io.kompose.service: influxdb
    spec:
      containers:
      - env:
        - name: GF_INSTALL_PLUGINS
          valueFrom:
            configMapKeyRef:
              key: GF_INSTALL_PLUGINS
              name: configuration-env
        - name: GF_SECURITY_ADMIN_PASSWORD
          valueFrom:
            configMapKeyRef:
              key: GF_SECURITY_ADMIN_PASSWORD
              name: configuration-env
        - name: GF_SECURITY_ADMIN_USER
          valueFrom:
            configMapKeyRef:
              key: GF_SECURITY_ADMIN_USER
              name: configuration-env
        - name: INFLUXDB_ADMIN_PASSWORD
          valueFrom:
            configMapKeyRef:
              key: INFLUXDB_ADMIN_PASSWORD
              name: configuration-env
        - name: INFLUXDB_ADMIN_USER
          valueFrom:
            configMapKeyRef:
              key: INFLUXDB_ADMIN_USER
              name: configuration-env
        - name: INFLUXDB_DB
          valueFrom:
            configMapKeyRef:
              key: INFLUXDB_DB
              name: configuration-env
        image: influxdb:1.8-alpine
        imagePullPolicy: ""
        name: influxdb
        ports:
        - containerPort: 8086
        resources: {}
        volumeMounts:
        - mountPath: /imports
          name: influxdb-claim0
        - mountPath: /var/lib/influxdb
          name: influxdb-data
      restartPolicy: Always
      serviceAccountName: ""
      volumes:
      - name: influxdb-claim0
        persistentVolumeClaim:
          claimName: influxdb-claim0
      - name: influxdb-data
        persistentVolumeClaim:
          claimName: influxdb-data
status: {}
