apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: /snap/kompose/19/kompose-linux-amd64 convert -f docker-compose.yml
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: chronograf
  name: chronograf
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: chronograf
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: /snap/kompose/19/kompose-linux-amd64 convert -f docker-compose.yml
        kompose.version: 1.21.0 (992df58d8)
      creationTimestamp: null
      labels:
        io.kompose.service: chronograf
    spec:
      containers:
      - env:
        - name: INFLUXDB_URL
          value: http://influxdb:8086
        - name: KAPACITOR_URL
          value: http://kapacitor:9092
        image: chronograf
        imagePullPolicy: ""
        name: chronograf
        ports:
        - containerPort: 8888
        resources: {}
      restartPolicy: Always
      serviceAccountName: ""
      volumes: null
status: {}
